### ISSUE TITLE
In Class Assignments VS Assignments

### ISSUE THREAD

**Issue by AllisonKSissom** [LaunchCodeEducation/technical-analyst-curriculum#25]
Need clarity on the difference between "In Class Assignments" and "Assignments." Also I don't know that I saw a rubric in the original google doc, each assignment should have a specific rubric for grading.
![Screenshot 2023-10-10 150548](https://github.com/LaunchCodeEducation/technical-analyst-curriculum/assets/146112740/6ddc8cf5-e901-4a35-96ff-6df309324d87)

**Comment by icr8FreeCode** [comment]
Addressed in latest PR
