### ISSUE TITLE
(On-site) Gradable Assignments and Participation

### ISSUE THREAD

**Issue by AllisonKSissom** [LaunchCodeEducation/technical-analyst-curriculum#26]
These points seem arbitrary.  Mock Interviews and Resumes should not be graded assignments. These people have already gotten the job, so they don't need to have a passing Mock Interview or Resume.
![Screenshot 2023-10-10 150937](https://github.com/LaunchCodeEducation/technical-analyst-curriculum/assets/146112740/e227a406-dd20-4700-a5f8-ba6894a79854)

**Comment by icr8FreeCode** [comment]
facts. removed
