### ISSUE TITLE
Active Listening: Empathy

### ISSUE THREAD

**Issue by AllisonKSissom** [LaunchCodeEducation/technical-analyst-curriculum#27]
I don't think this is a strong enough example. There is little to no difference between "Let me see what we can do" and "Let me see what I can do." Also, this is an opportunity to link to a video about how to show Emapthy or an article on Emapthy in customer service. An outside vetted source would be greatly beneficial. 
![Screenshot 2023-10-10 152342](https://github.com/LaunchCodeEducation/technical-analyst-curriculum/assets/146112740/28e9d9f5-7573-4184-9e8e-a7c338e6f152)

**Comment by icr8FreeCode** [comment]
Under consideration and review
