### ISSUE TITLE
Labeling

### ISSUE THREAD

**Issue by AllisonKSissom** [LaunchCodeEducation/technical-analyst-curriculum#28]
This paragraph doesn't say a lot about what labeling is or how to do it tactfully. I think it needs to be defined and then an example of how to do it.
![Screenshot 2023-10-10 152740](https://github.com/LaunchCodeEducation/technical-analyst-curriculum/assets/146112740/f79237ee-d07c-4d75-a8fd-47a20a4271b3)

**Comment by icr8FreeCode** [comment]
under consideration and review
