### ISSUE TITLE
Business Writing

### ISSUE THREAD

**Issue by AllisonKSissom** [LaunchCodeEducation/technical-analyst-curriculum#31]
Business Writing section should be grouped with Technical writing section on Day 6. It is not strong enough on it’s own and would pair better with Technical writing.
![Screenshot 2023-10-18 175901](https://github.com/LaunchCodeEducation/technical-analyst-curriculum/assets/146112740/6f51594f-ab01-4e87-8f2e-5830d4265a96)

**Comment by icr8FreeCode** [comment]
This is a huge content change and will not be addressed in this iteration of the course
