### ISSUE TITLE
CEM included in class activity

### ISSUE THREAD

**Issue by AllisonKSissom** [LaunchCodeEducation/technical-analyst-curriculum#32]
CEM should not be included in classroom activities. This should be led and reviewed by the Instructor of the course.
![Screenshot 2023-10-18 180112](https://github.com/LaunchCodeEducation/technical-analyst-curriculum/assets/146112740/8e0408db-7018-45e5-a770-a9992b20feeb)

**Comment by icr8FreeCode** [comment]
duplicate issue
