### ISSUE TITLE
No Teaching Assistant with this program.

### ISSUE THREAD

**Issue by AllisonKSissom** [LaunchCodeEducation/technical-analyst-curriculum#33]
There will not be a TA for this program, additionally the CEM should not be included, it should be the instructor. 
![Screenshot 2023-10-18 180227](https://github.com/LaunchCodeEducation/technical-analyst-curriculum/assets/146112740/75ae1879-f6c0-4373-9043-1bd93802258a)

**Comment by icr8FreeCode** [comment]
removed TA and email requirement
