### ISSUE TITLE
Confusing Wording 2nd paragraph Day 1

### ISSUE THREAD

**Issue by AllisonKSissom** [LaunchCodeEducation/technical-analyst-curriculum#36]
Confusing wording, don’t use the word to define the word. Suggested rewording:
We can also validate their experience through normalization of the situation, helping the speaker feel heard and that we understand the experience they are having during the interaction with us.
![Screenshot 2023-10-18 181008](https://github.com/LaunchCodeEducation/technical-analyst-curriculum/assets/146112740/c14fa453-131f-4632-8eb5-7031d07e980b)

**Comment by icr8FreeCode** [comment]
clarified sentence
