### ISSUE TITLE
Suggested Additional Activities Day 1

### ISSUE THREAD

**Issue by AllisonKSissom** [LaunchCodeEducation/technical-analyst-curriculum#37]
The reading and activities planned won't fill an 8 hour work day. These additional activities will help fill the morning session on Day 1. 
Technical Documentation activity: provide 3-4 technical documents with errors and have the students discuss as a group what is missing and needs improvement.

I strongly advise moving Module 2: Effective Communicatoin to afternoon of day 1. The activities listed won’t take a whole day. I would estimate they will take 2-3 hours total.

**Comment by icr8FreeCode** [comment]
Under consideration and review
