### ISSUE TITLE
Day 3 Paragraph 3

### ISSUE THREAD

**Issue by AllisonKSissom** [LaunchCodeEducation/technical-analyst-curriculum#40]
Affliction is not the right word. Suggested revision: intonation. 
![Screenshot 2023-10-18 181955](https://github.com/LaunchCodeEducation/technical-analyst-curriculum/assets/146112740/71c8c9f3-90e4-4e6b-a914-b9b030264ecf)
![Screenshot 2023-10-18 182054](https://github.com/LaunchCodeEducation/technical-analyst-curriculum/assets/146112740/17a46a71-47dc-4e38-b4e2-331cd8a68529)
![Screenshot 2023-10-18 182042](https://github.com/LaunchCodeEducation/technical-analyst-curriculum/assets/146112740/4a6dc552-eb84-4da8-9b26-28dacc31bc62)

**Comment by icr8FreeCode** [comment]
This should be inflection. thanks
