### ISSUE TITLE
Favorable Wins When Setting/Anchoring Expectations

### ISSUE THREAD

**Issue by AllisonKSissom** [LaunchCodeEducation/technical-analyst-curriculum#41]
Shouldn't lead with an example. It should be nestled under the first statement.
2nd statement should also have an example.

![Screenshot 2023-10-18 182715](https://github.com/LaunchCodeEducation/technical-analyst-curriculum/assets/146112740/c856ced2-490d-418e-8871-c0f305038232)

**Comment by icr8FreeCode** [comment]
move example as suggested
