### ISSUE TITLE
Day 5. Can't have an off day without good reason.

### ISSUE THREAD

**Issue by AllisonKSissom** [LaunchCodeEducation/technical-analyst-curriculum#44]
There can't be an off day without a good reason. I would suggest instead that students do presentations in AM and work-day in PM all in-person.
There could be an opportunity to pull small groups of students to get feedback, but students are getting paid to learn and should be learning or working.
There could be a 1hr session just for feedback?
![Screenshot 2023-10-18 183733](https://github.com/LaunchCodeEducation/technical-analyst-curriculum/assets/146112740/d65d255d-7f8c-46b8-9eb3-e8318f6aba69)

**Comment by icr8FreeCode** [comment]
this has been addressed
