### ISSUE TITLE
Salesforce - break apart across multiple days

### ISSUE THREAD

**Issue by AllisonKSissom** [LaunchCodeEducation/technical-analyst-curriculum#45]
Part 1 Modules = 1.5 hours
Part 2 Modules = 12 hours

I would recommend that Salesforce be spread across and done in the afternoon of each day: 
Day 1 Active Listening - Intro to Salesforce + SFModule 1-7 (~3.5 hrs)
Day 2: Handling Rejection - SF Modules 8-10 (~3.75 hrs)
Day 3 Questionable Empathy  - SF Modules 11-13 (~4 hrs)
Day 4 Work Day + Course Feedback- SF Modules 14-17 (~3.75 hrs)

**Comment by icr8FreeCode** [comment]
Issue addressed

**Comment by icr8FreeCode** [comment]
Addressed in latest PR
